//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The accord type represents the tuning of a single string in the scordatura element. It uses the same group of elements as the staff-tuning element. Strings are numbered from high to low.
 * 
 * <p>Java class for accord complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="accord">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <group ref="{}tuning"/>
 *       <attribute name="string" type="{}string-number" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accord", propOrder = {
    "tuningStep",
    "tuningAlter",
    "tuningOctave"
})
public class Accord {

    /**
     * The tuning-step element is represented like the step element, with a different name to reflect its different function in string tuning.
     * 
     */
    @XmlElement(name = "tuning-step", required = true)
    @XmlSchemaType(name = "string")
    protected Step tuningStep;
    /**
     * The tuning-alter element is represented like the alter element, with a different name to reflect its different function in string tuning.
     * 
     */
    @XmlElement(name = "tuning-alter")
    protected BigDecimal tuningAlter;
    /**
     * The tuning-octave element is represented like the octave element, with a different name to reflect its different function in string tuning.
     * 
     */
    @XmlElement(name = "tuning-octave")
    @XmlSchemaType(name = "integer")
    protected int tuningOctave;
    @XmlAttribute(name = "string")
    protected BigInteger string;

    /**
     * The tuning-step element is represented like the step element, with a different name to reflect its different function in string tuning.
     * 
     * @return
     *     possible object is
     *     {@link Step }
     *     
     */
    public Step getTuningStep() {
        return tuningStep;
    }

    /**
     * Sets the value of the tuningStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Step }
     *     
     * @see #getTuningStep()
     */
    public void setTuningStep(Step value) {
        this.tuningStep = value;
    }

    /**
     * The tuning-alter element is represented like the alter element, with a different name to reflect its different function in string tuning.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTuningAlter() {
        return tuningAlter;
    }

    /**
     * Sets the value of the tuningAlter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTuningAlter()
     */
    public void setTuningAlter(BigDecimal value) {
        this.tuningAlter = value;
    }

    /**
     * The tuning-octave element is represented like the octave element, with a different name to reflect its different function in string tuning.
     * 
     */
    public int getTuningOctave() {
        return tuningOctave;
    }

    /**
     * Sets the value of the tuningOctave property.
     * 
     */
    public void setTuningOctave(int value) {
        this.tuningOctave = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setString(BigInteger value) {
        this.string = value;
    }

}
