//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The arrow-style type represents the style of an arrow, using Unicode arrow terminology. Filled and hollow arrows indicate polygonal single arrows. Paired arrows are duplicate single arrows in the same direction. Combined arrows apply to double direction arrows like left right, indicating that an arrow in one direction should be combined with an arrow in the other direction.
 * 
 * <p>Java class for arrow-style</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="arrow-style">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="single"/>
 *     <enumeration value="double"/>
 *     <enumeration value="filled"/>
 *     <enumeration value="hollow"/>
 *     <enumeration value="paired"/>
 *     <enumeration value="combined"/>
 *     <enumeration value="other"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "arrow-style")
@XmlEnum
public enum ArrowStyle {

    @XmlEnumValue("single")
    SINGLE("single"),
    @XmlEnumValue("double")
    DOUBLE("double"),
    @XmlEnumValue("filled")
    FILLED("filled"),
    @XmlEnumValue("hollow")
    HOLLOW("hollow"),
    @XmlEnumValue("paired")
    PAIRED("paired"),
    @XmlEnumValue("combined")
    COMBINED("combined"),
    @XmlEnumValue("other")
    OTHER("other");
    private final java.lang.String value;

    ArrowStyle(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ArrowStyle fromValue(java.lang.String v) {
        for (ArrowStyle c: ArrowStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
