//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The arrow-direction type represents the direction in which an arrow points, using Unicode arrow terminology.
 * 
 * <p>Java class for arrow-direction</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="arrow-direction">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="left"/>
 *     <enumeration value="up"/>
 *     <enumeration value="right"/>
 *     <enumeration value="down"/>
 *     <enumeration value="northwest"/>
 *     <enumeration value="northeast"/>
 *     <enumeration value="southeast"/>
 *     <enumeration value="southwest"/>
 *     <enumeration value="left right"/>
 *     <enumeration value="up down"/>
 *     <enumeration value="northwest southeast"/>
 *     <enumeration value="northeast southwest"/>
 *     <enumeration value="other"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "arrow-direction")
@XmlEnum
public enum ArrowDirection {

    @XmlEnumValue("left")
    LEFT("left"),
    @XmlEnumValue("up")
    UP("up"),
    @XmlEnumValue("right")
    RIGHT("right"),
    @XmlEnumValue("down")
    DOWN("down"),
    @XmlEnumValue("northwest")
    NORTHWEST("northwest"),
    @XmlEnumValue("northeast")
    NORTHEAST("northeast"),
    @XmlEnumValue("southeast")
    SOUTHEAST("southeast"),
    @XmlEnumValue("southwest")
    SOUTHWEST("southwest"),
    @XmlEnumValue("left right")
    LEFT_RIGHT("left right"),
    @XmlEnumValue("up down")
    UP_DOWN("up down"),
    @XmlEnumValue("northwest southeast")
    NORTHWEST_SOUTHEAST("northwest southeast"),
    @XmlEnumValue("northeast southwest")
    NORTHEAST_SOUTHWEST("northeast southwest"),
    @XmlEnumValue("other")
    OTHER("other");
    private final java.lang.String value;

    ArrowDirection(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ArrowDirection fromValue(java.lang.String v) {
        for (ArrowDirection c: ArrowDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
