//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The bar-style type represents barline style information. Choices are regular, dotted, dashed, heavy, light-light, light-heavy, heavy-light, heavy-heavy, tick (a short stroke through the top line), short (a partial barline between the 2nd and 4th lines), and none.
 * 
 * <p>Java class for bar-style</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="bar-style">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="regular"/>
 *     <enumeration value="dotted"/>
 *     <enumeration value="dashed"/>
 *     <enumeration value="heavy"/>
 *     <enumeration value="light-light"/>
 *     <enumeration value="light-heavy"/>
 *     <enumeration value="heavy-light"/>
 *     <enumeration value="heavy-heavy"/>
 *     <enumeration value="tick"/>
 *     <enumeration value="short"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "bar-style")
@XmlEnum
public enum BarStyle {

    @XmlEnumValue("regular")
    REGULAR("regular"),
    @XmlEnumValue("dotted")
    DOTTED("dotted"),
    @XmlEnumValue("dashed")
    DASHED("dashed"),
    @XmlEnumValue("heavy")
    HEAVY("heavy"),
    @XmlEnumValue("light-light")
    LIGHT_LIGHT("light-light"),
    @XmlEnumValue("light-heavy")
    LIGHT_HEAVY("light-heavy"),
    @XmlEnumValue("heavy-light")
    HEAVY_LIGHT("heavy-light"),
    @XmlEnumValue("heavy-heavy")
    HEAVY_HEAVY("heavy-heavy"),
    @XmlEnumValue("tick")
    TICK("tick"),
    @XmlEnumValue("short")
    SHORT("short"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    BarStyle(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static BarStyle fromValue(java.lang.String v) {
        for (BarStyle c: BarStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
