//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The beam-value type represents the type of beam associated with each of 8 beam levels (up to 1024th notes) available for each note.
 * 
 * <p>Java class for beam-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="beam-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="begin"/>
 *     <enumeration value="continue"/>
 *     <enumeration value="end"/>
 *     <enumeration value="forward hook"/>
 *     <enumeration value="backward hook"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "beam-value")
@XmlEnum
public enum BeamValue {

    @XmlEnumValue("begin")
    BEGIN("begin"),
    @XmlEnumValue("continue")
    CONTINUE("continue"),
    @XmlEnumValue("end")
    END("end"),
    @XmlEnumValue("forward hook")
    FORWARD_HOOK("forward hook"),
    @XmlEnumValue("backward hook")
    BACKWARD_HOOK("backward hook");
    private final java.lang.String value;

    BeamValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static BeamValue fromValue(java.lang.String v) {
        for (BeamValue c: BeamValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
