//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The beater-value type represents pictograms for beaters, mallets, and sticks that do not have different materials represented in the pictogram. The finger and hammer values are in addition to Stone's list.
 * 
 * <p>Java class for beater-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="beater-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="bow"/>
 *     <enumeration value="chime hammer"/>
 *     <enumeration value="coin"/>
 *     <enumeration value="drum stick"/>
 *     <enumeration value="finger"/>
 *     <enumeration value="fingernail"/>
 *     <enumeration value="fist"/>
 *     <enumeration value="guiro scraper"/>
 *     <enumeration value="hammer"/>
 *     <enumeration value="hand"/>
 *     <enumeration value="jazz stick"/>
 *     <enumeration value="knitting needle"/>
 *     <enumeration value="metal hammer"/>
 *     <enumeration value="slide brush on gong"/>
 *     <enumeration value="snare stick"/>
 *     <enumeration value="spoon mallet"/>
 *     <enumeration value="superball"/>
 *     <enumeration value="triangle beater"/>
 *     <enumeration value="triangle beater plain"/>
 *     <enumeration value="wire brush"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "beater-value")
@XmlEnum
public enum BeaterValue {

    @XmlEnumValue("bow")
    BOW("bow"),
    @XmlEnumValue("chime hammer")
    CHIME_HAMMER("chime hammer"),
    @XmlEnumValue("coin")
    COIN("coin"),
    @XmlEnumValue("drum stick")
    DRUM_STICK("drum stick"),
    @XmlEnumValue("finger")
    FINGER("finger"),
    @XmlEnumValue("fingernail")
    FINGERNAIL("fingernail"),
    @XmlEnumValue("fist")
    FIST("fist"),
    @XmlEnumValue("guiro scraper")
    GUIRO_SCRAPER("guiro scraper"),
    @XmlEnumValue("hammer")
    HAMMER("hammer"),
    @XmlEnumValue("hand")
    HAND("hand"),
    @XmlEnumValue("jazz stick")
    JAZZ_STICK("jazz stick"),
    @XmlEnumValue("knitting needle")
    KNITTING_NEEDLE("knitting needle"),
    @XmlEnumValue("metal hammer")
    METAL_HAMMER("metal hammer"),
    @XmlEnumValue("slide brush on gong")
    SLIDE_BRUSH_ON_GONG("slide brush on gong"),
    @XmlEnumValue("snare stick")
    SNARE_STICK("snare stick"),
    @XmlEnumValue("spoon mallet")
    SPOON_MALLET("spoon mallet"),
    @XmlEnumValue("superball")
    SUPERBALL("superball"),
    @XmlEnumValue("triangle beater")
    TRIANGLE_BEATER("triangle beater"),
    @XmlEnumValue("triangle beater plain")
    TRIANGLE_BEATER_PLAIN("triangle beater plain"),
    @XmlEnumValue("wire brush")
    WIRE_BRUSH("wire brush");
    private final java.lang.String value;

    BeaterValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static BeaterValue fromValue(java.lang.String v) {
        for (BeaterValue c: BeaterValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
