//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The clef-sign type represents the different clef symbols. The jianpu sign indicates that the music that follows should be in jianpu numbered notation, just as the TAB sign indicates that the music that follows should be in tablature notation. Unlike TAB, a jianpu sign does not correspond to a visual clef notation.
 * 
 * The none sign is deprecated as of MusicXML 4.0. Use the clef element's print-object attribute instead. When the none sign is used, notes should be displayed as if in treble clef.
 * 
 * <p>Java class for clef-sign</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="clef-sign">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="G"/>
 *     <enumeration value="F"/>
 *     <enumeration value="C"/>
 *     <enumeration value="percussion"/>
 *     <enumeration value="TAB"/>
 *     <enumeration value="jianpu"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "clef-sign")
@XmlEnum
public enum ClefSign {

    G("G"),
    F("F"),
    C("C"),
    @XmlEnumValue("percussion")
    PERCUSSION("percussion"),
    TAB("TAB"),
    @XmlEnumValue("jianpu")
    JIANPU("jianpu"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    ClefSign(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ClefSign fromValue(java.lang.String v) {
        for (ClefSign c: ClefSign.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
