//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The degree-symbol-value type indicates which symbol should be used in specifying a degree.
 * 
 * <p>Java class for degree-symbol-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="degree-symbol-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="major"/>
 *     <enumeration value="minor"/>
 *     <enumeration value="augmented"/>
 *     <enumeration value="diminished"/>
 *     <enumeration value="half-diminished"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "degree-symbol-value")
@XmlEnum
public enum DegreeSymbolValue {

    @XmlEnumValue("major")
    MAJOR("major"),
    @XmlEnumValue("minor")
    MINOR("minor"),
    @XmlEnumValue("augmented")
    AUGMENTED("augmented"),
    @XmlEnumValue("diminished")
    DIMINISHED("diminished"),
    @XmlEnumValue("half-diminished")
    HALF_DIMINISHED("half-diminished");
    private final java.lang.String value;

    DegreeSymbolValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static DegreeSymbolValue fromValue(java.lang.String v) {
        for (DegreeSymbolValue c: DegreeSymbolValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
