//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The enclosure-shape type describes the shape and presence / absence of an enclosure around text or symbols. A bracket enclosure is similar to a rectangle with the bottom line missing, as is common in jazz notation. An inverted-bracket enclosure is similar to a rectangle with the top line missing.
 * 
 * <p>Java class for enclosure-shape</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="enclosure-shape">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="rectangle"/>
 *     <enumeration value="square"/>
 *     <enumeration value="oval"/>
 *     <enumeration value="circle"/>
 *     <enumeration value="bracket"/>
 *     <enumeration value="inverted-bracket"/>
 *     <enumeration value="triangle"/>
 *     <enumeration value="diamond"/>
 *     <enumeration value="pentagon"/>
 *     <enumeration value="hexagon"/>
 *     <enumeration value="heptagon"/>
 *     <enumeration value="octagon"/>
 *     <enumeration value="nonagon"/>
 *     <enumeration value="decagon"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "enclosure-shape")
@XmlEnum
public enum EnclosureShape {

    @XmlEnumValue("rectangle")
    RECTANGLE("rectangle"),
    @XmlEnumValue("square")
    SQUARE("square"),
    @XmlEnumValue("oval")
    OVAL("oval"),
    @XmlEnumValue("circle")
    CIRCLE("circle"),
    @XmlEnumValue("bracket")
    BRACKET("bracket"),
    @XmlEnumValue("inverted-bracket")
    INVERTED_BRACKET("inverted-bracket"),
    @XmlEnumValue("triangle")
    TRIANGLE("triangle"),
    @XmlEnumValue("diamond")
    DIAMOND("diamond"),
    @XmlEnumValue("pentagon")
    PENTAGON("pentagon"),
    @XmlEnumValue("hexagon")
    HEXAGON("hexagon"),
    @XmlEnumValue("heptagon")
    HEPTAGON("heptagon"),
    @XmlEnumValue("octagon")
    OCTAGON("octagon"),
    @XmlEnumValue("nonagon")
    NONAGON("nonagon"),
    @XmlEnumValue("decagon")
    DECAGON("decagon"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    EnclosureShape(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static EnclosureShape fromValue(java.lang.String v) {
        for (EnclosureShape c: EnclosureShape.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
