//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * The encoding element contains information about who did the digital encoding, when, with what software, and in what aspects. Standard type values for the encoder element are music, words, and arrangement, but other types may be used. The type attribute is only needed when there are multiple encoder elements.
 * 
 * <p>Java class for encoding complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="encoding">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="encoding-date" type="{}yyyy-mm-dd"/>
 *         <element name="encoder" type="{}typed-text"/>
 *         <element name="software" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="encoding-description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="supports" type="{}supports"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "encoding", propOrder = {
    "encodingDateOrEncoderOrSoftware"
})
public class Encoding {

    @XmlElementRefs({
        @XmlElementRef(name = "encoding-date", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "encoder", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "software", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "encoding-description", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "supports", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> encodingDateOrEncoderOrSoftware;

    /**
     * Gets the value of the encodingDateOrEncoderOrSoftware property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encodingDateOrEncoderOrSoftware property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEncodingDateOrEncoderOrSoftware().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link Supports }{@code >}
     * {@link JAXBElement }{@code <}{@link TypedText }{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the encodingDateOrEncoderOrSoftware property.
     */
    public List<JAXBElement<?>> getEncodingDateOrEncoderOrSoftware() {
        if (encodingDateOrEncoderOrSoftware == null) {
            encodingDateOrEncoderOrSoftware = new ArrayList<>();
        }
        return this.encodingDateOrEncoderOrSoftware;
    }

}
