//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The fan type represents the type of beam fanning present on a note, used to represent accelerandos and ritardandos.
 * 
 * <p>Java class for fan</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="fan">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="accel"/>
 *     <enumeration value="rit"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "fan")
@XmlEnum
public enum Fan {

    @XmlEnumValue("accel")
    ACCEL("accel"),
    @XmlEnumValue("rit")
    RIT("rit"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    Fan(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static Fan fromValue(java.lang.String v) {
        for (Fan c: Fan.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
