//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The glass-value type represents pictograms for glass percussion instruments.
 * 
 * <p>Java class for glass-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="glass-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="glass harmonica"/>
 *     <enumeration value="glass harp"/>
 *     <enumeration value="wind chimes"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "glass-value")
@XmlEnum
public enum GlassValue {

    @XmlEnumValue("glass harmonica")
    GLASS_HARMONICA("glass harmonica"),
    @XmlEnumValue("glass harp")
    GLASS_HARP("glass harp"),
    @XmlEnumValue("wind chimes")
    WIND_CHIMES("wind chimes");
    private final java.lang.String value;

    GlassValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static GlassValue fromValue(java.lang.String v) {
        for (GlassValue c: GlassValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
