//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The group-symbol-value type indicates how the symbol for a group or multi-staff part is indicated in the score.
 * 
 * <p>Java class for group-symbol-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="group-symbol-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="none"/>
 *     <enumeration value="brace"/>
 *     <enumeration value="line"/>
 *     <enumeration value="bracket"/>
 *     <enumeration value="square"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "group-symbol-value")
@XmlEnum
public enum GroupSymbolValue {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("brace")
    BRACE("brace"),
    @XmlEnumValue("line")
    LINE("line"),
    @XmlEnumValue("bracket")
    BRACKET("bracket"),
    @XmlEnumValue("square")
    SQUARE("square");
    private final java.lang.String value;

    GroupSymbolValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static GroupSymbolValue fromValue(java.lang.String v) {
        for (GroupSymbolValue c: GroupSymbolValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
