//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The handbell-value type represents the type of handbell technique being notated.
 * 
 * <p>Java class for handbell-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="handbell-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="belltree"/>
 *     <enumeration value="damp"/>
 *     <enumeration value="echo"/>
 *     <enumeration value="gyro"/>
 *     <enumeration value="hand martellato"/>
 *     <enumeration value="mallet lift"/>
 *     <enumeration value="mallet table"/>
 *     <enumeration value="martellato"/>
 *     <enumeration value="martellato lift"/>
 *     <enumeration value="muted martellato"/>
 *     <enumeration value="pluck lift"/>
 *     <enumeration value="swing"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "handbell-value")
@XmlEnum
public enum HandbellValue {

    @XmlEnumValue("belltree")
    BELLTREE("belltree"),
    @XmlEnumValue("damp")
    DAMP("damp"),
    @XmlEnumValue("echo")
    ECHO("echo"),
    @XmlEnumValue("gyro")
    GYRO("gyro"),
    @XmlEnumValue("hand martellato")
    HAND_MARTELLATO("hand martellato"),
    @XmlEnumValue("mallet lift")
    MALLET_LIFT("mallet lift"),
    @XmlEnumValue("mallet table")
    MALLET_TABLE("mallet table"),
    @XmlEnumValue("martellato")
    MARTELLATO("martellato"),
    @XmlEnumValue("martellato lift")
    MARTELLATO_LIFT("martellato lift"),
    @XmlEnumValue("muted martellato")
    MUTED_MARTELLATO("muted martellato"),
    @XmlEnumValue("pluck lift")
    PLUCK_LIFT("pluck lift"),
    @XmlEnumValue("swing")
    SWING("swing");
    private final java.lang.String value;

    HandbellValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static HandbellValue fromValue(java.lang.String v) {
        for (HandbellValue c: HandbellValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
