//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The harmonic type indicates natural and artificial harmonics. Allowing the type of pitch to be specified, combined with controls for appearance/playback differences, allows both the notation and the sound to be represented. Artificial harmonics can add a notated touching pitch; artificial pinch harmonics will usually not notate a touching pitch. The attributes for the harmonic element refer to the use of the circular harmonic symbol, typically but not always used with natural harmonics.
 * 
 * <p>Java class for harmonic complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="harmonic">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice minOccurs="0">
 *           <element name="natural" type="{}empty"/>
 *           <element name="artificial" type="{}empty"/>
 *         </choice>
 *         <choice minOccurs="0">
 *           <element name="base-pitch" type="{}empty"/>
 *           <element name="touching-pitch" type="{}empty"/>
 *           <element name="sounding-pitch" type="{}empty"/>
 *         </choice>
 *       </sequence>
 *       <attGroup ref="{}print-object"/>
 *       <attGroup ref="{}print-style"/>
 *       <attGroup ref="{}placement"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "harmonic", propOrder = {
    "natural",
    "artificial",
    "basePitch",
    "touchingPitch",
    "soundingPitch"
})
public class Harmonic {

    /**
     * The natural element indicates that this is a natural harmonic. These are usually notated at base pitch rather than sounding pitch.
     * 
     */
    protected Empty natural;
    /**
     * The artificial element indicates that this is an artificial harmonic.
     * 
     */
    protected Empty artificial;
    /**
     * The base pitch is the pitch at which the string is played before touching to create the harmonic.
     * 
     */
    @XmlElement(name = "base-pitch")
    protected Empty basePitch;
    /**
     * The touching-pitch is the pitch at which the string is touched lightly to produce the harmonic.
     * 
     */
    @XmlElement(name = "touching-pitch")
    protected Empty touchingPitch;
    /**
     * The sounding-pitch is the pitch which is heard when playing the harmonic.
     * 
     */
    @XmlElement(name = "sounding-pitch")
    protected Empty soundingPitch;
    @XmlAttribute(name = "print-object")
    protected YesNo printObject;
    @XmlAttribute(name = "font-family")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String fontFamily;
    @XmlAttribute(name = "font-style")
    protected FontStyle fontStyle;
    @XmlAttribute(name = "font-size")
    protected java.lang.String fontSize;
    @XmlAttribute(name = "font-weight")
    protected FontWeight fontWeight;
    @XmlAttribute(name = "default-x")
    protected BigDecimal defaultX;
    @XmlAttribute(name = "default-y")
    protected BigDecimal defaultY;
    @XmlAttribute(name = "relative-x")
    protected BigDecimal relativeX;
    @XmlAttribute(name = "relative-y")
    protected BigDecimal relativeY;
    @XmlAttribute(name = "color")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String color;
    @XmlAttribute(name = "placement")
    protected AboveBelow placement;

    /**
     * The natural element indicates that this is a natural harmonic. These are usually notated at base pitch rather than sounding pitch.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getNatural() {
        return natural;
    }

    /**
     * Sets the value of the natural property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getNatural()
     */
    public void setNatural(Empty value) {
        this.natural = value;
    }

    /**
     * The artificial element indicates that this is an artificial harmonic.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getArtificial() {
        return artificial;
    }

    /**
     * Sets the value of the artificial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getArtificial()
     */
    public void setArtificial(Empty value) {
        this.artificial = value;
    }

    /**
     * The base pitch is the pitch at which the string is played before touching to create the harmonic.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getBasePitch() {
        return basePitch;
    }

    /**
     * Sets the value of the basePitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getBasePitch()
     */
    public void setBasePitch(Empty value) {
        this.basePitch = value;
    }

    /**
     * The touching-pitch is the pitch at which the string is touched lightly to produce the harmonic.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getTouchingPitch() {
        return touchingPitch;
    }

    /**
     * Sets the value of the touchingPitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getTouchingPitch()
     */
    public void setTouchingPitch(Empty value) {
        this.touchingPitch = value;
    }

    /**
     * The sounding-pitch is the pitch which is heard when playing the harmonic.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getSoundingPitch() {
        return soundingPitch;
    }

    /**
     * Sets the value of the soundingPitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getSoundingPitch()
     */
    public void setSoundingPitch(Empty value) {
        this.soundingPitch = value;
    }

    /**
     * Gets the value of the printObject property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintObject() {
        return printObject;
    }

    /**
     * Sets the value of the printObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintObject(YesNo value) {
        this.printObject = value;
    }

    /**
     * Gets the value of the fontFamily property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFontFamily() {
        return fontFamily;
    }

    /**
     * Sets the value of the fontFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFontFamily(java.lang.String value) {
        this.fontFamily = value;
    }

    /**
     * Gets the value of the fontStyle property.
     * 
     * @return
     *     possible object is
     *     {@link FontStyle }
     *     
     */
    public FontStyle getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FontStyle }
     *     
     */
    public void setFontStyle(FontStyle value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFontSize(java.lang.String value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontWeight property.
     * 
     * @return
     *     possible object is
     *     {@link FontWeight }
     *     
     */
    public FontWeight getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link FontWeight }
     *     
     */
    public void setFontWeight(FontWeight value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the defaultX property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDefaultX() {
        return defaultX;
    }

    /**
     * Sets the value of the defaultX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDefaultX(BigDecimal value) {
        this.defaultX = value;
    }

    /**
     * Gets the value of the defaultY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDefaultY() {
        return defaultY;
    }

    /**
     * Sets the value of the defaultY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDefaultY(BigDecimal value) {
        this.defaultY = value;
    }

    /**
     * Gets the value of the relativeX property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelativeX() {
        return relativeX;
    }

    /**
     * Sets the value of the relativeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelativeX(BigDecimal value) {
        this.relativeX = value;
    }

    /**
     * Gets the value of the relativeY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelativeY() {
        return relativeY;
    }

    /**
     * Sets the value of the relativeY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelativeY(BigDecimal value) {
        this.relativeY = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setColor(java.lang.String value) {
        this.color = value;
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link AboveBelow }
     *     
     */
    public AboveBelow getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AboveBelow }
     *     
     */
    public void setPlacement(AboveBelow value) {
        this.placement = value;
    }

}
