//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * The harmon-closed type represents whether the harmon mute is closed, open, or half-open. The optional location attribute indicates which portion of the symbol is filled in when the element value is half.
 * 
 * <p>Java class for harmon-closed complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="harmon-closed">
 *   <simpleContent>
 *     <extension base="<>harmon-closed-value">
 *       <attribute name="location" type="{}harmon-closed-location" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "harmon-closed", propOrder = {
    "value"
})
public class HarmonClosed {

    /**
     * The harmon-closed-value type represents whether the harmon mute is closed, open, or half-open.
     * 
     */
    @XmlValue
    protected HarmonClosedValue value;
    @XmlAttribute(name = "location")
    protected HarmonClosedLocation location;

    /**
     * The harmon-closed-value type represents whether the harmon mute is closed, open, or half-open.
     * 
     * @return
     *     possible object is
     *     {@link HarmonClosedValue }
     *     
     */
    public HarmonClosedValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link HarmonClosedValue }
     *     
     * @see #getValue()
     */
    public void setValue(HarmonClosedValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link HarmonClosedLocation }
     *     
     */
    public HarmonClosedLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link HarmonClosedLocation }
     *     
     */
    public void setLocation(HarmonClosedLocation value) {
        this.location = value;
    }

}
