//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The hole-closed-location type indicates which portion of the hole is filled in when the corresponding hole-closed-value is half.
 * 
 * <p>Java class for hole-closed-location</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="hole-closed-location">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="right"/>
 *     <enumeration value="bottom"/>
 *     <enumeration value="left"/>
 *     <enumeration value="top"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "hole-closed-location")
@XmlEnum
public enum HoleClosedLocation {

    @XmlEnumValue("right")
    RIGHT("right"),
    @XmlEnumValue("bottom")
    BOTTOM("bottom"),
    @XmlEnumValue("left")
    LEFT("left"),
    @XmlEnumValue("top")
    TOP("top");
    private final java.lang.String value;

    HoleClosedLocation(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static HoleClosedLocation fromValue(java.lang.String v) {
        for (HoleClosedLocation c: HoleClosedLocation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
