//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The instrument-change element type represents a change to the virtual instrument sound for a given score-instrument. The id attribute refers to the score-instrument affected by the change. All instrument-change child elements can also be initially specified within the score-instrument element.
 * 
 * <p>Java class for instrument-change complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="instrument-change">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <group ref="{}virtual-instrument-data"/>
 *       <attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instrument-change", propOrder = {
    "instrumentSound",
    "solo",
    "ensemble",
    "virtualInstrument"
})
public class InstrumentChange {

    /**
     * The instrument-sound element describes the default timbre of the score-instrument. This description is independent of a particular virtual or MIDI instrument specification and allows playback to be shared more easily between applications and libraries.
     * 
     */
    @XmlElement(name = "instrument-sound")
    protected java.lang.String instrumentSound;
    /**
     * The solo element is present if performance is intended by a solo instrument.
     * 
     */
    protected Empty solo;
    /**
     * The ensemble element is present if performance is intended by an ensemble such as an orchestral section. The text of the ensemble element contains the size of the section, or is empty if the ensemble size is not specified.
     * 
     */
    protected java.lang.String ensemble;
    @XmlElement(name = "virtual-instrument")
    protected VirtualInstrument virtualInstrument;
    @XmlAttribute(name = "id", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object id;

    /**
     * The instrument-sound element describes the default timbre of the score-instrument. This description is independent of a particular virtual or MIDI instrument specification and allows playback to be shared more easily between applications and libraries.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getInstrumentSound() {
        return instrumentSound;
    }

    /**
     * Sets the value of the instrumentSound property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     * @see #getInstrumentSound()
     */
    public void setInstrumentSound(java.lang.String value) {
        this.instrumentSound = value;
    }

    /**
     * The solo element is present if performance is intended by a solo instrument.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getSolo() {
        return solo;
    }

    /**
     * Sets the value of the solo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getSolo()
     */
    public void setSolo(Empty value) {
        this.solo = value;
    }

    /**
     * The ensemble element is present if performance is intended by an ensemble such as an orchestral section. The text of the ensemble element contains the size of the section, or is empty if the ensemble size is not specified.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEnsemble() {
        return ensemble;
    }

    /**
     * Sets the value of the ensemble property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     * @see #getEnsemble()
     */
    public void setEnsemble(java.lang.String value) {
        this.ensemble = value;
    }

    /**
     * Gets the value of the virtualInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualInstrument }
     *     
     */
    public VirtualInstrument getVirtualInstrument() {
        return virtualInstrument;
    }

    /**
     * Sets the value of the virtualInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualInstrument }
     *     
     */
    public void setVirtualInstrument(VirtualInstrument value) {
        this.virtualInstrument = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setId(Object value) {
        this.id = value;
    }

}
