//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * A kind-value indicates the type of chord. Degree elements can then add, subtract, or alter from these starting points. Values include:
 * 
 * Triads:
 * 	major (major third, perfect fifth)
 * 	minor (minor third, perfect fifth)
 * 	augmented (major third, augmented fifth)
 * 	diminished (minor third, diminished fifth)
 * Sevenths:
 * 	dominant (major triad, minor seventh)
 * 	major-seventh (major triad, major seventh)
 * 	minor-seventh (minor triad, minor seventh)
 * 	diminished-seventh (diminished triad, diminished seventh)
 * 	augmented-seventh (augmented triad, minor seventh)
 * 	half-diminished (diminished triad, minor seventh)
 * 	major-minor (minor triad, major seventh)
 * Sixths:
 * 	major-sixth (major triad, added sixth)
 * 	minor-sixth (minor triad, added sixth)
 * Ninths:
 * 	dominant-ninth (dominant-seventh, major ninth)
 * 	major-ninth (major-seventh, major ninth)
 * 	minor-ninth (minor-seventh, major ninth)
 *  11ths (usually as the basis for alteration):
 * 	dominant-11th (dominant-ninth, perfect 11th)
 * 	major-11th (major-ninth, perfect 11th)
 * 	minor-11th (minor-ninth, perfect 11th)
 *  13ths (usually as the basis for alteration):
 * 	dominant-13th (dominant-11th, major 13th)
 * 	major-13th (major-11th, major 13th)
 * 	minor-13th (minor-11th, major 13th)
 * Suspended:
 * 	suspended-second (major second, perfect fifth)
 * 	suspended-fourth (perfect fourth, perfect fifth)
 * Functional sixths:
 * 	Neapolitan
 * 	Italian
 * 	French
 * 	German
 * Other:
 * 	pedal (pedal-point bass)
 * 	power (perfect fifth)
 * 	Tristan
 * 
 * The "other" kind is used when the harmony is entirely composed of add elements.
 * 
 * The "none" kind is used to explicitly encode absence of chords or functional harmony. In this case, the root, numeral, or function element has no meaning. When using the root or numeral element, the root-step or numeral-step text attribute should be set to the empty string to keep the root or numeral from being displayed.
 * 
 * <p>Java class for kind-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="kind-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="major"/>
 *     <enumeration value="minor"/>
 *     <enumeration value="augmented"/>
 *     <enumeration value="diminished"/>
 *     <enumeration value="dominant"/>
 *     <enumeration value="major-seventh"/>
 *     <enumeration value="minor-seventh"/>
 *     <enumeration value="diminished-seventh"/>
 *     <enumeration value="augmented-seventh"/>
 *     <enumeration value="half-diminished"/>
 *     <enumeration value="major-minor"/>
 *     <enumeration value="major-sixth"/>
 *     <enumeration value="minor-sixth"/>
 *     <enumeration value="dominant-ninth"/>
 *     <enumeration value="major-ninth"/>
 *     <enumeration value="minor-ninth"/>
 *     <enumeration value="dominant-11th"/>
 *     <enumeration value="major-11th"/>
 *     <enumeration value="minor-11th"/>
 *     <enumeration value="dominant-13th"/>
 *     <enumeration value="major-13th"/>
 *     <enumeration value="minor-13th"/>
 *     <enumeration value="suspended-second"/>
 *     <enumeration value="suspended-fourth"/>
 *     <enumeration value="Neapolitan"/>
 *     <enumeration value="Italian"/>
 *     <enumeration value="French"/>
 *     <enumeration value="German"/>
 *     <enumeration value="pedal"/>
 *     <enumeration value="power"/>
 *     <enumeration value="Tristan"/>
 *     <enumeration value="other"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "kind-value")
@XmlEnum
public enum KindValue {

    @XmlEnumValue("major")
    MAJOR("major"),
    @XmlEnumValue("minor")
    MINOR("minor"),
    @XmlEnumValue("augmented")
    AUGMENTED("augmented"),
    @XmlEnumValue("diminished")
    DIMINISHED("diminished"),
    @XmlEnumValue("dominant")
    DOMINANT("dominant"),
    @XmlEnumValue("major-seventh")
    MAJOR_SEVENTH("major-seventh"),
    @XmlEnumValue("minor-seventh")
    MINOR_SEVENTH("minor-seventh"),
    @XmlEnumValue("diminished-seventh")
    DIMINISHED_SEVENTH("diminished-seventh"),
    @XmlEnumValue("augmented-seventh")
    AUGMENTED_SEVENTH("augmented-seventh"),
    @XmlEnumValue("half-diminished")
    HALF_DIMINISHED("half-diminished"),
    @XmlEnumValue("major-minor")
    MAJOR_MINOR("major-minor"),
    @XmlEnumValue("major-sixth")
    MAJOR_SIXTH("major-sixth"),
    @XmlEnumValue("minor-sixth")
    MINOR_SIXTH("minor-sixth"),
    @XmlEnumValue("dominant-ninth")
    DOMINANT_NINTH("dominant-ninth"),
    @XmlEnumValue("major-ninth")
    MAJOR_NINTH("major-ninth"),
    @XmlEnumValue("minor-ninth")
    MINOR_NINTH("minor-ninth"),
    @XmlEnumValue("dominant-11th")
    DOMINANT_11_TH("dominant-11th"),
    @XmlEnumValue("major-11th")
    MAJOR_11_TH("major-11th"),
    @XmlEnumValue("minor-11th")
    MINOR_11_TH("minor-11th"),
    @XmlEnumValue("dominant-13th")
    DOMINANT_13_TH("dominant-13th"),
    @XmlEnumValue("major-13th")
    MAJOR_13_TH("major-13th"),
    @XmlEnumValue("minor-13th")
    MINOR_13_TH("minor-13th"),
    @XmlEnumValue("suspended-second")
    SUSPENDED_SECOND("suspended-second"),
    @XmlEnumValue("suspended-fourth")
    SUSPENDED_FOURTH("suspended-fourth"),
    @XmlEnumValue("Neapolitan")
    NEAPOLITAN("Neapolitan"),
    @XmlEnumValue("Italian")
    ITALIAN("Italian"),
    @XmlEnumValue("French")
    FRENCH("French"),
    @XmlEnumValue("German")
    GERMAN("German"),
    @XmlEnumValue("pedal")
    PEDAL("pedal"),
    @XmlEnumValue("power")
    POWER("power"),
    @XmlEnumValue("Tristan")
    TRISTAN("Tristan"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    KindValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static KindValue fromValue(java.lang.String v) {
        for (KindValue c: KindValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
