//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The line-length type distinguishes between different line lengths for doit, falloff, plop, and scoop articulations.
 * 
 * <p>Java class for line-length</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="line-length">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="short"/>
 *     <enumeration value="medium"/>
 *     <enumeration value="long"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "line-length")
@XmlEnum
public enum LineLength {

    @XmlEnumValue("short")
    SHORT("short"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("long")
    LONG("long");
    private final java.lang.String value;

    LineLength(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static LineLength fromValue(java.lang.String v) {
        for (LineLength c: LineLength.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
