//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The membrane-value type represents pictograms for membrane percussion instruments.
 * 
 * <p>Java class for membrane-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="membrane-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="bass drum"/>
 *     <enumeration value="bass drum on side"/>
 *     <enumeration value="bongos"/>
 *     <enumeration value="Chinese tomtom"/>
 *     <enumeration value="conga drum"/>
 *     <enumeration value="cuica"/>
 *     <enumeration value="goblet drum"/>
 *     <enumeration value="Indo-American tomtom"/>
 *     <enumeration value="Japanese tomtom"/>
 *     <enumeration value="military drum"/>
 *     <enumeration value="snare drum"/>
 *     <enumeration value="snare drum snares off"/>
 *     <enumeration value="tabla"/>
 *     <enumeration value="tambourine"/>
 *     <enumeration value="tenor drum"/>
 *     <enumeration value="timbales"/>
 *     <enumeration value="tomtom"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "membrane-value")
@XmlEnum
public enum MembraneValue {

    @XmlEnumValue("bass drum")
    BASS_DRUM("bass drum"),
    @XmlEnumValue("bass drum on side")
    BASS_DRUM_ON_SIDE("bass drum on side"),
    @XmlEnumValue("bongos")
    BONGOS("bongos"),
    @XmlEnumValue("Chinese tomtom")
    CHINESE_TOMTOM("Chinese tomtom"),
    @XmlEnumValue("conga drum")
    CONGA_DRUM("conga drum"),
    @XmlEnumValue("cuica")
    CUICA("cuica"),
    @XmlEnumValue("goblet drum")
    GOBLET_DRUM("goblet drum"),
    @XmlEnumValue("Indo-American tomtom")
    INDO_AMERICAN_TOMTOM("Indo-American tomtom"),
    @XmlEnumValue("Japanese tomtom")
    JAPANESE_TOMTOM("Japanese tomtom"),
    @XmlEnumValue("military drum")
    MILITARY_DRUM("military drum"),
    @XmlEnumValue("snare drum")
    SNARE_DRUM("snare drum"),
    @XmlEnumValue("snare drum snares off")
    SNARE_DRUM_SNARES_OFF("snare drum snares off"),
    @XmlEnumValue("tabla")
    TABLA("tabla"),
    @XmlEnumValue("tambourine")
    TAMBOURINE("tambourine"),
    @XmlEnumValue("tenor drum")
    TENOR_DRUM("tenor drum"),
    @XmlEnumValue("timbales")
    TIMBALES("timbales"),
    @XmlEnumValue("tomtom")
    TOMTOM("tomtom");
    private final java.lang.String value;

    MembraneValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static MembraneValue fromValue(java.lang.String v) {
        for (MembraneValue c: MembraneValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
