//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * The metronome-beam type works like the beam type in defining metric relationships, but does not include all the attributes available in the beam type.
 * 
 * <p>Java class for metronome-beam complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="metronome-beam">
 *   <simpleContent>
 *     <extension base="<>beam-value">
 *       <attribute name="number" type="{}beam-level" default="1" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metronome-beam", propOrder = {
    "value"
})
public class MetronomeBeam {

    /**
     * The beam-value type represents the type of beam associated with each of 8 beam levels (up to 1024th notes) available for each note.
     * 
     */
    @XmlValue
    protected BeamValue value;
    @XmlAttribute(name = "number")
    protected Integer number;

    /**
     * The beam-value type represents the type of beam associated with each of 8 beam levels (up to 1024th notes) available for each note.
     * 
     * @return
     *     possible object is
     *     {@link BeamValue }
     *     
     */
    public BeamValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeamValue }
     *     
     * @see #getValue()
     */
    public void setValue(BeamValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumber() {
        if (number == null) {
            return  1;
        } else {
            return number;
        }
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumber(Integer value) {
        this.number = value;
    }

}
