//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The midi-instrument type defines MIDI 1.0 instrument playback. The midi-instrument element can be a part of either the score-instrument element at the start of a part, or the sound element within a part. The id attribute refers to the score-instrument affected by the change.
 * 
 * <p>Java class for midi-instrument complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="midi-instrument">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="midi-channel" type="{}midi-16" minOccurs="0"/>
 *         <element name="midi-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="midi-bank" type="{}midi-16384" minOccurs="0"/>
 *         <element name="midi-program" type="{}midi-128" minOccurs="0"/>
 *         <element name="midi-unpitched" type="{}midi-128" minOccurs="0"/>
 *         <element name="volume" type="{}percent" minOccurs="0"/>
 *         <element name="pan" type="{}rotation-degrees" minOccurs="0"/>
 *         <element name="elevation" type="{}rotation-degrees" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "midi-instrument", propOrder = {
    "midiChannel",
    "midiName",
    "midiBank",
    "midiProgram",
    "midiUnpitched",
    "volume",
    "pan",
    "elevation"
})
public class MidiInstrument {

    /**
     * The midi-channel element specifies a MIDI 1.0 channel numbers ranging from 1 to 16.
     * 
     */
    @XmlElement(name = "midi-channel")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer midiChannel;
    /**
     * The midi-name element corresponds to a ProgramName meta-event within a Standard MIDI File.
     * 
     */
    @XmlElement(name = "midi-name")
    protected java.lang.String midiName;
    /**
     * The midi-bank element specifies a MIDI 1.0 bank number ranging from 1 to 16,384.
     * 
     */
    @XmlElement(name = "midi-bank")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer midiBank;
    /**
     * The midi-program element specifies a MIDI 1.0 program number ranging from 1 to 128.
     * 
     */
    @XmlElement(name = "midi-program")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer midiProgram;
    /**
     * For unpitched instruments, the midi-unpitched element specifies a MIDI 1.0 note number ranging from 1 to 128. It is usually used with MIDI banks for percussion. Note that MIDI 1.0 note numbers are generally specified from 0 to 127 rather than the 1 to 128 numbering used in this element.
     * 
     */
    @XmlElement(name = "midi-unpitched")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer midiUnpitched;
    /**
     * The volume element value is a percentage of the maximum ranging from 0 to 100, with decimal values allowed. This corresponds to a scaling value for the MIDI 1.0 channel volume controller.
     * 
     */
    protected BigDecimal volume;
    /**
     * The pan and elevation elements allow placing of sound in a 3-D space relative to the listener. Both are expressed in degrees ranging from -180 to 180. For pan, 0 is straight ahead, -90 is hard left, 90 is hard right, and -180 and 180 are directly behind the listener.
     * 
     */
    protected BigDecimal pan;
    /**
     * The elevation and pan elements allow placing of sound in a 3-D space relative to the listener. Both are expressed in degrees ranging from -180 to 180. For elevation, 0 is level with the listener, 90 is directly above, and -90 is directly below.
     * 
     */
    protected BigDecimal elevation;
    @XmlAttribute(name = "id", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object id;

    /**
     * The midi-channel element specifies a MIDI 1.0 channel numbers ranging from 1 to 16.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMidiChannel() {
        return midiChannel;
    }

    /**
     * Sets the value of the midiChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getMidiChannel()
     */
    public void setMidiChannel(Integer value) {
        this.midiChannel = value;
    }

    /**
     * The midi-name element corresponds to a ProgramName meta-event within a Standard MIDI File.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMidiName() {
        return midiName;
    }

    /**
     * Sets the value of the midiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     * @see #getMidiName()
     */
    public void setMidiName(java.lang.String value) {
        this.midiName = value;
    }

    /**
     * The midi-bank element specifies a MIDI 1.0 bank number ranging from 1 to 16,384.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMidiBank() {
        return midiBank;
    }

    /**
     * Sets the value of the midiBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getMidiBank()
     */
    public void setMidiBank(Integer value) {
        this.midiBank = value;
    }

    /**
     * The midi-program element specifies a MIDI 1.0 program number ranging from 1 to 128.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMidiProgram() {
        return midiProgram;
    }

    /**
     * Sets the value of the midiProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getMidiProgram()
     */
    public void setMidiProgram(Integer value) {
        this.midiProgram = value;
    }

    /**
     * For unpitched instruments, the midi-unpitched element specifies a MIDI 1.0 note number ranging from 1 to 128. It is usually used with MIDI banks for percussion. Note that MIDI 1.0 note numbers are generally specified from 0 to 127 rather than the 1 to 128 numbering used in this element.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMidiUnpitched() {
        return midiUnpitched;
    }

    /**
     * Sets the value of the midiUnpitched property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getMidiUnpitched()
     */
    public void setMidiUnpitched(Integer value) {
        this.midiUnpitched = value;
    }

    /**
     * The volume element value is a percentage of the maximum ranging from 0 to 100, with decimal values allowed. This corresponds to a scaling value for the MIDI 1.0 channel volume controller.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getVolume()
     */
    public void setVolume(BigDecimal value) {
        this.volume = value;
    }

    /**
     * The pan and elevation elements allow placing of sound in a 3-D space relative to the listener. Both are expressed in degrees ranging from -180 to 180. For pan, 0 is straight ahead, -90 is hard left, 90 is hard right, and -180 and 180 are directly behind the listener.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPan() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPan()
     */
    public void setPan(BigDecimal value) {
        this.pan = value;
    }

    /**
     * The elevation and pan elements allow placing of sound in a 3-D space relative to the listener. Both are expressed in degrees ranging from -180 to 180. For elevation, 0 is level with the listener, 90 is directly above, and -90 is directly below.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getElevation()
     */
    public void setElevation(BigDecimal value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setId(Object value) {
        this.id = value;
    }

}
