//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The mute type represents muting for different instruments, including brass, winds, and strings. The on and off values are used for undifferentiated mutes. The remaining values represent specific mutes.
 * 
 * <p>Java class for mute</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="mute">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="on"/>
 *     <enumeration value="off"/>
 *     <enumeration value="straight"/>
 *     <enumeration value="cup"/>
 *     <enumeration value="harmon-no-stem"/>
 *     <enumeration value="harmon-stem"/>
 *     <enumeration value="bucket"/>
 *     <enumeration value="plunger"/>
 *     <enumeration value="hat"/>
 *     <enumeration value="solotone"/>
 *     <enumeration value="practice"/>
 *     <enumeration value="stop-mute"/>
 *     <enumeration value="stop-hand"/>
 *     <enumeration value="echo"/>
 *     <enumeration value="palm"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "mute")
@XmlEnum
public enum Mute {

    @XmlEnumValue("on")
    ON("on"),
    @XmlEnumValue("off")
    OFF("off"),
    @XmlEnumValue("straight")
    STRAIGHT("straight"),
    @XmlEnumValue("cup")
    CUP("cup"),
    @XmlEnumValue("harmon-no-stem")
    HARMON_NO_STEM("harmon-no-stem"),
    @XmlEnumValue("harmon-stem")
    HARMON_STEM("harmon-stem"),
    @XmlEnumValue("bucket")
    BUCKET("bucket"),
    @XmlEnumValue("plunger")
    PLUNGER("plunger"),
    @XmlEnumValue("hat")
    HAT("hat"),
    @XmlEnumValue("solotone")
    SOLOTONE("solotone"),
    @XmlEnumValue("practice")
    PRACTICE("practice"),
    @XmlEnumValue("stop-mute")
    STOP_MUTE("stop-mute"),
    @XmlEnumValue("stop-hand")
    STOP_HAND("stop-hand"),
    @XmlEnumValue("echo")
    ECHO("echo"),
    @XmlEnumValue("palm")
    PALM("palm");
    private final java.lang.String value;

    Mute(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static Mute fromValue(java.lang.String v) {
        for (Mute c: Mute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
