//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for note complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="note">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="grace" type="{}grace" minOccurs="0"/>
 *         <element name="cue" type="{}empty" minOccurs="0"/>
 *         <group ref="{}full-note" minOccurs="0"/>
 *         <group ref="{}duration" minOccurs="0"/>
 *         <element name="tie" type="{}tie" maxOccurs="2" minOccurs="0"/>
 *         <element name="instrument" type="{}instrument" maxOccurs="unbounded" minOccurs="0"/>
 *         <group ref="{}editorial-voice" minOccurs="0"/>
 *         <element name="type" type="{}note-type" minOccurs="0"/>
 *         <element name="dot" type="{}empty-placement" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="accidental" type="{}accidental" minOccurs="0"/>
 *         <element name="time-modification" type="{}time-modification" minOccurs="0"/>
 *         <element name="stem" type="{}stem" minOccurs="0"/>
 *         <element name="notehead" type="{}notehead" minOccurs="0"/>
 *         <element name="notehead-text" type="{}notehead-text" minOccurs="0"/>
 *         <group ref="{}staff" minOccurs="0"/>
 *         <element name="beam" type="{}beam" maxOccurs="8" minOccurs="0"/>
 *         <element name="notations" type="{}notations" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="lyric" type="{}lyric" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="play" type="{}play" minOccurs="0"/>
 *         <element name="listen" type="{}listen" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{}color"/>
 *       <attGroup ref="{}font"/>
 *       <attGroup ref="{}printout"/>
 *       <attGroup ref="{}optional-unique-id"/>
 *       <attGroup ref="{}x-position"/>
 *       <attribute name="print-leger" type="{}yes-no" />
 *       <attribute name="dynamics" type="{}non-negative-decimal" />
 *       <attribute name="end-dynamics" type="{}non-negative-decimal" />
 *       <attribute name="attack" type="{}divisions" />
 *       <attribute name="release" type="{}divisions" />
 *       <attribute name="time-only" type="{}time-only" />
 *       <attribute name="pizzicato" type="{}yes-no" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "note", propOrder = {
    "grace",
    "cue",
    "chord",
    "pitch",
    "unpitched",
    "rest",
    "duration",
    "tie",
    "instrument",
    "footnote",
    "level",
    "voice",
    "type",
    "dot",
    "accidental",
    "timeModification",
    "stem",
    "notehead",
    "noteheadText",
    "staff",
    "beam",
    "notations",
    "lyric",
    "play",
    "listen"
})
public class Note {

    protected Grace grace;
    protected Empty cue;
    /**
     * The chord element indicates that this note is an additional chord tone with the preceding note.
     * 
     * The duration of a chord note does not move the musical position within a measure. That is done by the duration of the first preceding note without a chord element. Thus the duration of a chord note cannot be longer than the preceding note.
     * 
     * In most cases the duration will be the same as the preceding note. However it can be shorter in situations such as multiple stops for string instruments.
     * 
     */
    protected Empty chord;
    protected Pitch pitch;
    protected Unpitched unpitched;
    protected Rest rest;
    /**
     * Duration is a positive number specified in division units. This is the intended duration vs. notated duration (for instance, differences in dotted notes in Baroque-era music). Differences in duration specific to an interpretation or performance should be represented using the note element's attack and release attributes.
     * 
     * The duration element moves the musical position when used in backup elements, forward elements, and note elements that do not contain a chord child element.
     * 
     */
    protected BigDecimal duration;
    protected List<Tie> tie;
    protected List<Instrument> instrument;
    protected FormattedText footnote;
    protected Level level;
    protected java.lang.String voice;
    protected NoteType type;
    protected List<EmptyPlacement> dot;
    protected Accidental accidental;
    @XmlElement(name = "time-modification")
    protected TimeModification timeModification;
    protected Stem stem;
    protected Notehead notehead;
    @XmlElement(name = "notehead-text")
    protected NoteheadText noteheadText;
    /**
     * Staff assignment is only needed for music notated on multiple staves. Used by both notes and directions. Staff values are numbers, with 1 referring to the top-most staff in a part.
     * 
     */
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger staff;
    protected List<Beam> beam;
    protected List<Notations> notations;
    protected List<Lyric> lyric;
    protected Play play;
    protected Listen listen;
    @XmlAttribute(name = "print-leger")
    protected YesNo printLeger;
    @XmlAttribute(name = "dynamics")
    protected BigDecimal dynamics;
    @XmlAttribute(name = "end-dynamics")
    protected BigDecimal endDynamics;
    @XmlAttribute(name = "attack")
    protected BigDecimal attack;
    @XmlAttribute(name = "release")
    protected BigDecimal release;
    @XmlAttribute(name = "time-only")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String timeOnly;
    @XmlAttribute(name = "pizzicato")
    protected YesNo pizzicato;
    @XmlAttribute(name = "color")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String color;
    @XmlAttribute(name = "font-family")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String fontFamily;
    @XmlAttribute(name = "font-style")
    protected FontStyle fontStyle;
    @XmlAttribute(name = "font-size")
    protected java.lang.String fontSize;
    @XmlAttribute(name = "font-weight")
    protected FontWeight fontWeight;
    @XmlAttribute(name = "print-dot")
    protected YesNo printDot;
    @XmlAttribute(name = "print-lyric")
    protected YesNo printLyric;
    @XmlAttribute(name = "print-spacing")
    protected YesNo printSpacing;
    @XmlAttribute(name = "print-object")
    protected YesNo printObject;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;
    @XmlAttribute(name = "default-x")
    protected BigDecimal defaultX;
    @XmlAttribute(name = "default-y")
    protected BigDecimal defaultY;
    @XmlAttribute(name = "relative-x")
    protected BigDecimal relativeX;
    @XmlAttribute(name = "relative-y")
    protected BigDecimal relativeY;

    /**
     * Gets the value of the grace property.
     * 
     * @return
     *     possible object is
     *     {@link Grace }
     *     
     */
    public Grace getGrace() {
        return grace;
    }

    /**
     * Sets the value of the grace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grace }
     *     
     */
    public void setGrace(Grace value) {
        this.grace = value;
    }

    /**
     * Gets the value of the cue property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getCue() {
        return cue;
    }

    /**
     * Sets the value of the cue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setCue(Empty value) {
        this.cue = value;
    }

    /**
     * The chord element indicates that this note is an additional chord tone with the preceding note.
     * 
     * The duration of a chord note does not move the musical position within a measure. That is done by the duration of the first preceding note without a chord element. Thus the duration of a chord note cannot be longer than the preceding note.
     * 
     * In most cases the duration will be the same as the preceding note. However it can be shorter in situations such as multiple stops for string instruments.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getChord() {
        return chord;
    }

    /**
     * Sets the value of the chord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     * @see #getChord()
     */
    public void setChord(Empty value) {
        this.chord = value;
    }

    /**
     * Gets the value of the pitch property.
     * 
     * @return
     *     possible object is
     *     {@link Pitch }
     *     
     */
    public Pitch getPitch() {
        return pitch;
    }

    /**
     * Sets the value of the pitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pitch }
     *     
     */
    public void setPitch(Pitch value) {
        this.pitch = value;
    }

    /**
     * Gets the value of the unpitched property.
     * 
     * @return
     *     possible object is
     *     {@link Unpitched }
     *     
     */
    public Unpitched getUnpitched() {
        return unpitched;
    }

    /**
     * Sets the value of the unpitched property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unpitched }
     *     
     */
    public void setUnpitched(Unpitched value) {
        this.unpitched = value;
    }

    /**
     * Gets the value of the rest property.
     * 
     * @return
     *     possible object is
     *     {@link Rest }
     *     
     */
    public Rest getRest() {
        return rest;
    }

    /**
     * Sets the value of the rest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rest }
     *     
     */
    public void setRest(Rest value) {
        this.rest = value;
    }

    /**
     * Duration is a positive number specified in division units. This is the intended duration vs. notated duration (for instance, differences in dotted notes in Baroque-era music). Differences in duration specific to an interpretation or performance should be represented using the note element's attack and release attributes.
     * 
     * The duration element moves the musical position when used in backup elements, forward elements, and note elements that do not contain a chord child element.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getDuration()
     */
    public void setDuration(BigDecimal value) {
        this.duration = value;
    }

    /**
     * Gets the value of the tie property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tie property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tie }
     * </p>
     * 
     * 
     * @return
     *     The value of the tie property.
     */
    public List<Tie> getTie() {
        if (tie == null) {
            tie = new ArrayList<>();
        }
        return this.tie;
    }

    /**
     * Gets the value of the instrument property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instrument property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInstrument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Instrument }
     * </p>
     * 
     * 
     * @return
     *     The value of the instrument property.
     */
    public List<Instrument> getInstrument() {
        if (instrument == null) {
            instrument = new ArrayList<>();
        }
        return this.instrument;
    }

    /**
     * Gets the value of the footnote property.
     * 
     * @return
     *     possible object is
     *     {@link FormattedText }
     *     
     */
    public FormattedText getFootnote() {
        return footnote;
    }

    /**
     * Sets the value of the footnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormattedText }
     *     
     */
    public void setFootnote(FormattedText value) {
        this.footnote = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Level }
     *     
     */
    public Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level }
     *     
     */
    public void setLevel(Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the voice property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getVoice() {
        return voice;
    }

    /**
     * Sets the value of the voice property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setVoice(java.lang.String value) {
        this.voice = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link NoteType }
     *     
     */
    public NoteType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteType }
     *     
     */
    public void setType(NoteType value) {
        this.type = value;
    }

    /**
     * Gets the value of the dot property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dot property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmptyPlacement }
     * </p>
     * 
     * 
     * @return
     *     The value of the dot property.
     */
    public List<EmptyPlacement> getDot() {
        if (dot == null) {
            dot = new ArrayList<>();
        }
        return this.dot;
    }

    /**
     * Gets the value of the accidental property.
     * 
     * @return
     *     possible object is
     *     {@link Accidental }
     *     
     */
    public Accidental getAccidental() {
        return accidental;
    }

    /**
     * Sets the value of the accidental property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accidental }
     *     
     */
    public void setAccidental(Accidental value) {
        this.accidental = value;
    }

    /**
     * Gets the value of the timeModification property.
     * 
     * @return
     *     possible object is
     *     {@link TimeModification }
     *     
     */
    public TimeModification getTimeModification() {
        return timeModification;
    }

    /**
     * Sets the value of the timeModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeModification }
     *     
     */
    public void setTimeModification(TimeModification value) {
        this.timeModification = value;
    }

    /**
     * Gets the value of the stem property.
     * 
     * @return
     *     possible object is
     *     {@link Stem }
     *     
     */
    public Stem getStem() {
        return stem;
    }

    /**
     * Sets the value of the stem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stem }
     *     
     */
    public void setStem(Stem value) {
        this.stem = value;
    }

    /**
     * Gets the value of the notehead property.
     * 
     * @return
     *     possible object is
     *     {@link Notehead }
     *     
     */
    public Notehead getNotehead() {
        return notehead;
    }

    /**
     * Sets the value of the notehead property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notehead }
     *     
     */
    public void setNotehead(Notehead value) {
        this.notehead = value;
    }

    /**
     * Gets the value of the noteheadText property.
     * 
     * @return
     *     possible object is
     *     {@link NoteheadText }
     *     
     */
    public NoteheadText getNoteheadText() {
        return noteheadText;
    }

    /**
     * Sets the value of the noteheadText property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteheadText }
     *     
     */
    public void setNoteheadText(NoteheadText value) {
        this.noteheadText = value;
    }

    /**
     * Staff assignment is only needed for music notated on multiple staves. Used by both notes and directions. Staff values are numbers, with 1 referring to the top-most staff in a part.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStaff() {
        return staff;
    }

    /**
     * Sets the value of the staff property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getStaff()
     */
    public void setStaff(BigInteger value) {
        this.staff = value;
    }

    /**
     * Gets the value of the beam property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beam property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBeam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Beam }
     * </p>
     * 
     * 
     * @return
     *     The value of the beam property.
     */
    public List<Beam> getBeam() {
        if (beam == null) {
            beam = new ArrayList<>();
        }
        return this.beam;
    }

    /**
     * Gets the value of the notations property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notations property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notations }
     * </p>
     * 
     * 
     * @return
     *     The value of the notations property.
     */
    public List<Notations> getNotations() {
        if (notations == null) {
            notations = new ArrayList<>();
        }
        return this.notations;
    }

    /**
     * Gets the value of the lyric property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lyric property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLyric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lyric }
     * </p>
     * 
     * 
     * @return
     *     The value of the lyric property.
     */
    public List<Lyric> getLyric() {
        if (lyric == null) {
            lyric = new ArrayList<>();
        }
        return this.lyric;
    }

    /**
     * Gets the value of the play property.
     * 
     * @return
     *     possible object is
     *     {@link Play }
     *     
     */
    public Play getPlay() {
        return play;
    }

    /**
     * Sets the value of the play property.
     * 
     * @param value
     *     allowed object is
     *     {@link Play }
     *     
     */
    public void setPlay(Play value) {
        this.play = value;
    }

    /**
     * Gets the value of the listen property.
     * 
     * @return
     *     possible object is
     *     {@link Listen }
     *     
     */
    public Listen getListen() {
        return listen;
    }

    /**
     * Sets the value of the listen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Listen }
     *     
     */
    public void setListen(Listen value) {
        this.listen = value;
    }

    /**
     * Gets the value of the printLeger property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintLeger() {
        return printLeger;
    }

    /**
     * Sets the value of the printLeger property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintLeger(YesNo value) {
        this.printLeger = value;
    }

    /**
     * Gets the value of the dynamics property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDynamics() {
        return dynamics;
    }

    /**
     * Sets the value of the dynamics property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDynamics(BigDecimal value) {
        this.dynamics = value;
    }

    /**
     * Gets the value of the endDynamics property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndDynamics() {
        return endDynamics;
    }

    /**
     * Sets the value of the endDynamics property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndDynamics(BigDecimal value) {
        this.endDynamics = value;
    }

    /**
     * Gets the value of the attack property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAttack() {
        return attack;
    }

    /**
     * Sets the value of the attack property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAttack(BigDecimal value) {
        this.attack = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelease(BigDecimal value) {
        this.release = value;
    }

    /**
     * Gets the value of the timeOnly property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTimeOnly() {
        return timeOnly;
    }

    /**
     * Sets the value of the timeOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTimeOnly(java.lang.String value) {
        this.timeOnly = value;
    }

    /**
     * Gets the value of the pizzicato property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPizzicato() {
        return pizzicato;
    }

    /**
     * Sets the value of the pizzicato property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPizzicato(YesNo value) {
        this.pizzicato = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setColor(java.lang.String value) {
        this.color = value;
    }

    /**
     * Gets the value of the fontFamily property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFontFamily() {
        return fontFamily;
    }

    /**
     * Sets the value of the fontFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFontFamily(java.lang.String value) {
        this.fontFamily = value;
    }

    /**
     * Gets the value of the fontStyle property.
     * 
     * @return
     *     possible object is
     *     {@link FontStyle }
     *     
     */
    public FontStyle getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FontStyle }
     *     
     */
    public void setFontStyle(FontStyle value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFontSize(java.lang.String value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the fontWeight property.
     * 
     * @return
     *     possible object is
     *     {@link FontWeight }
     *     
     */
    public FontWeight getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link FontWeight }
     *     
     */
    public void setFontWeight(FontWeight value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the printDot property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintDot() {
        return printDot;
    }

    /**
     * Sets the value of the printDot property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintDot(YesNo value) {
        this.printDot = value;
    }

    /**
     * Gets the value of the printLyric property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintLyric() {
        return printLyric;
    }

    /**
     * Sets the value of the printLyric property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintLyric(YesNo value) {
        this.printLyric = value;
    }

    /**
     * Gets the value of the printSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintSpacing() {
        return printSpacing;
    }

    /**
     * Sets the value of the printSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintSpacing(YesNo value) {
        this.printSpacing = value;
    }

    /**
     * Gets the value of the printObject property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintObject() {
        return printObject;
    }

    /**
     * Sets the value of the printObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintObject(YesNo value) {
        this.printObject = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the defaultX property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDefaultX() {
        return defaultX;
    }

    /**
     * Sets the value of the defaultX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDefaultX(BigDecimal value) {
        this.defaultX = value;
    }

    /**
     * Gets the value of the defaultY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDefaultY() {
        return defaultY;
    }

    /**
     * Sets the value of the defaultY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDefaultY(BigDecimal value) {
        this.defaultY = value;
    }

    /**
     * Gets the value of the relativeX property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelativeX() {
        return relativeX;
    }

    /**
     * Sets the value of the relativeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelativeX(BigDecimal value) {
        this.relativeX = value;
    }

    /**
     * Gets the value of the relativeY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelativeY() {
        return relativeY;
    }

    /**
     * Sets the value of the relativeY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelativeY(BigDecimal value) {
        this.relativeY = value;
    }

}
