//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The notehead-value type indicates shapes other than the open and closed ovals associated with note durations.
 * 
 * The values do, re, mi, fa, fa up, so, la, and ti correspond to Aikin's 7-shape system.  The fa up shape is typically used with upstems; the fa shape is typically used with downstems or no stems.
 * 
 * The arrow shapes differ from triangle and inverted triangle by being centered on the stem. Slashed and back slashed notes include both the normal notehead and a slash. The triangle shape has the tip of the triangle pointing up; the inverted triangle shape has the tip of the triangle pointing down. The left triangle shape is a right triangle with the hypotenuse facing up and to the left.
 * 
 * The other notehead covers noteheads other than those listed here. It is usually used in combination with the smufl attribute to specify a particular SMuFL notehead. The smufl attribute may be used with any notehead value to help specify the appearance of symbols that share the same MusicXML semantics. Noteheads in the SMuFL Note name noteheads and Note name noteheads supplement ranges (U+E150–U+E1AF and U+EEE0–U+EEFF) should not use the smufl attribute or the "other" value, but instead use the notehead-text element.
 * 
 * <p>Java class for notehead-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="notehead-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="slash"/>
 *     <enumeration value="triangle"/>
 *     <enumeration value="diamond"/>
 *     <enumeration value="square"/>
 *     <enumeration value="cross"/>
 *     <enumeration value="x"/>
 *     <enumeration value="circle-x"/>
 *     <enumeration value="inverted triangle"/>
 *     <enumeration value="arrow down"/>
 *     <enumeration value="arrow up"/>
 *     <enumeration value="circled"/>
 *     <enumeration value="slashed"/>
 *     <enumeration value="back slashed"/>
 *     <enumeration value="normal"/>
 *     <enumeration value="cluster"/>
 *     <enumeration value="circle dot"/>
 *     <enumeration value="left triangle"/>
 *     <enumeration value="rectangle"/>
 *     <enumeration value="none"/>
 *     <enumeration value="do"/>
 *     <enumeration value="re"/>
 *     <enumeration value="mi"/>
 *     <enumeration value="fa"/>
 *     <enumeration value="fa up"/>
 *     <enumeration value="so"/>
 *     <enumeration value="la"/>
 *     <enumeration value="ti"/>
 *     <enumeration value="other"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "notehead-value")
@XmlEnum
public enum NoteheadValue {

    @XmlEnumValue("slash")
    SLASH("slash"),
    @XmlEnumValue("triangle")
    TRIANGLE("triangle"),
    @XmlEnumValue("diamond")
    DIAMOND("diamond"),
    @XmlEnumValue("square")
    SQUARE("square"),
    @XmlEnumValue("cross")
    CROSS("cross"),
    @XmlEnumValue("x")
    X("x"),
    @XmlEnumValue("circle-x")
    CIRCLE_X("circle-x"),
    @XmlEnumValue("inverted triangle")
    INVERTED_TRIANGLE("inverted triangle"),
    @XmlEnumValue("arrow down")
    ARROW_DOWN("arrow down"),
    @XmlEnumValue("arrow up")
    ARROW_UP("arrow up"),
    @XmlEnumValue("circled")
    CIRCLED("circled"),
    @XmlEnumValue("slashed")
    SLASHED("slashed"),
    @XmlEnumValue("back slashed")
    BACK_SLASHED("back slashed"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("cluster")
    CLUSTER("cluster"),
    @XmlEnumValue("circle dot")
    CIRCLE_DOT("circle dot"),
    @XmlEnumValue("left triangle")
    LEFT_TRIANGLE("left triangle"),
    @XmlEnumValue("rectangle")
    RECTANGLE("rectangle"),
    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("do")
    DO("do"),
    @XmlEnumValue("re")
    RE("re"),
    @XmlEnumValue("mi")
    MI("mi"),
    @XmlEnumValue("fa")
    FA("fa"),
    @XmlEnumValue("fa up")
    FA_UP("fa up"),
    @XmlEnumValue("so")
    SO("so"),
    @XmlEnumValue("la")
    LA("la"),
    @XmlEnumValue("ti")
    TI("ti"),
    @XmlEnumValue("other")
    OTHER("other");
    private final java.lang.String value;

    NoteheadValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static NoteheadValue fromValue(java.lang.String v) {
        for (NoteheadValue c: NoteheadValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
