//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The numeral type represents the Roman numeral or Nashville number part of a harmony. It requires that the key be specified in the encoding, either with a key or numeral-key element.
 * 
 * <p>Java class for numeral complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="numeral">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="numeral-root" type="{}numeral-root"/>
 *         <element name="numeral-alter" type="{}harmony-alter" minOccurs="0"/>
 *         <element name="numeral-key" type="{}numeral-key" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "numeral", propOrder = {
    "numeralRoot",
    "numeralAlter",
    "numeralKey"
})
public class Numeral {

    @XmlElement(name = "numeral-root", required = true)
    protected NumeralRoot numeralRoot;
    /**
     * The numeral-alter element represents an alteration to the numeral-root, similar to the alter element for a pitch. The print-object attribute can be used to hide an alteration in cases such as when the MusicXML encoding of a 6 or 7 numeral-root in a minor key requires an alteration that is not displayed. The location attribute indicates whether the alteration should appear to the left or the right of the numeral-root. It is left by default.
     * 
     */
    @XmlElement(name = "numeral-alter")
    protected HarmonyAlter numeralAlter;
    @XmlElement(name = "numeral-key")
    protected NumeralKey numeralKey;

    /**
     * Gets the value of the numeralRoot property.
     * 
     * @return
     *     possible object is
     *     {@link NumeralRoot }
     *     
     */
    public NumeralRoot getNumeralRoot() {
        return numeralRoot;
    }

    /**
     * Sets the value of the numeralRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumeralRoot }
     *     
     */
    public void setNumeralRoot(NumeralRoot value) {
        this.numeralRoot = value;
    }

    /**
     * The numeral-alter element represents an alteration to the numeral-root, similar to the alter element for a pitch. The print-object attribute can be used to hide an alteration in cases such as when the MusicXML encoding of a 6 or 7 numeral-root in a minor key requires an alteration that is not displayed. The location attribute indicates whether the alteration should appear to the left or the right of the numeral-root. It is left by default.
     * 
     * @return
     *     possible object is
     *     {@link HarmonyAlter }
     *     
     */
    public HarmonyAlter getNumeralAlter() {
        return numeralAlter;
    }

    /**
     * Sets the value of the numeralAlter property.
     * 
     * @param value
     *     allowed object is
     *     {@link HarmonyAlter }
     *     
     * @see #getNumeralAlter()
     */
    public void setNumeralAlter(HarmonyAlter value) {
        this.numeralAlter = value;
    }

    /**
     * Gets the value of the numeralKey property.
     * 
     * @return
     *     possible object is
     *     {@link NumeralKey }
     *     
     */
    public NumeralKey getNumeralKey() {
        return numeralKey;
    }

    /**
     * Sets the value of the numeralKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumeralKey }
     *     
     */
    public void setNumeralKey(NumeralKey value) {
        this.numeralKey = value;
    }

}
