//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The child elements of the part-clef type have the same meaning as for the clef type. However that meaning applies to a transposed part created from the existing score file.
 * 
 * <p>Java class for part-clef complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="part-clef">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <group ref="{}clef"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "part-clef", propOrder = {
    "sign",
    "line",
    "clefOctaveChange"
})
public class PartClef {

    /**
     * The sign element represents the clef symbol.
     * 
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ClefSign sign;
    /**
     * Line numbers are counted from the bottom of the staff. They are only needed with the G, F, and C signs in order to position a pitch correctly on the staff. Standard values are 2 for the G sign (treble clef), 4 for the F sign (bass clef), and 3 for the C sign (alto clef). Line values can be used to specify positions outside the staff, such as a C clef positioned in the middle of a grand staff.
     * 
     */
    protected BigInteger line;
    /**
     * The clef-octave-change element is used for transposing clefs. A treble clef for tenors would have a value of -1.
     * 
     */
    @XmlElement(name = "clef-octave-change")
    protected BigInteger clefOctaveChange;

    /**
     * The sign element represents the clef symbol.
     * 
     * @return
     *     possible object is
     *     {@link ClefSign }
     *     
     */
    public ClefSign getSign() {
        return sign;
    }

    /**
     * Sets the value of the sign property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClefSign }
     *     
     * @see #getSign()
     */
    public void setSign(ClefSign value) {
        this.sign = value;
    }

    /**
     * Line numbers are counted from the bottom of the staff. They are only needed with the G, F, and C signs in order to position a pitch correctly on the staff. Standard values are 2 for the G sign (treble clef), 4 for the F sign (bass clef), and 3 for the C sign (alto clef). Line values can be used to specify positions outside the staff, such as a C clef positioned in the middle of a grand staff.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getLine()
     */
    public void setLine(BigInteger value) {
        this.line = value;
    }

    /**
     * The clef-octave-change element is used for transposing clefs. A treble clef for tenors would have a value of -1.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClefOctaveChange() {
        return clefOctaveChange;
    }

    /**
     * Sets the value of the clefOctaveChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getClefOctaveChange()
     */
    public void setClefOctaveChange(BigInteger value) {
        this.clefOctaveChange = value;
    }

}
