//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The pitched-value type represents pictograms for pitched percussion instruments. The chimes and tubular chimes values distinguish the single-line and double-line versions of the pictogram.
 * 
 * <p>Java class for pitched-value</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="pitched-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="celesta"/>
 *     <enumeration value="chimes"/>
 *     <enumeration value="glockenspiel"/>
 *     <enumeration value="lithophone"/>
 *     <enumeration value="mallet"/>
 *     <enumeration value="marimba"/>
 *     <enumeration value="steel drums"/>
 *     <enumeration value="tubaphone"/>
 *     <enumeration value="tubular chimes"/>
 *     <enumeration value="vibraphone"/>
 *     <enumeration value="xylophone"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "pitched-value")
@XmlEnum
public enum PitchedValue {

    @XmlEnumValue("celesta")
    CELESTA("celesta"),
    @XmlEnumValue("chimes")
    CHIMES("chimes"),
    @XmlEnumValue("glockenspiel")
    GLOCKENSPIEL("glockenspiel"),
    @XmlEnumValue("lithophone")
    LITHOPHONE("lithophone"),
    @XmlEnumValue("mallet")
    MALLET("mallet"),
    @XmlEnumValue("marimba")
    MARIMBA("marimba"),
    @XmlEnumValue("steel drums")
    STEEL_DRUMS("steel drums"),
    @XmlEnumValue("tubaphone")
    TUBAPHONE("tubaphone"),
    @XmlEnumValue("tubular chimes")
    TUBULAR_CHIMES("tubular chimes"),
    @XmlEnumValue("vibraphone")
    VIBRAPHONE("vibraphone"),
    @XmlEnumValue("xylophone")
    XYLOPHONE("xylophone");
    private final java.lang.String value;

    PitchedValue(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static PitchedValue fromValue(java.lang.String v) {
        for (PitchedValue c: PitchedValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
