//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The principal-voice-symbol type represents the type of symbol used to indicate a principal or secondary voice. The "plain" value represents a plain square bracket. The value of "none" is used for analysis markup when the principal-voice element does not have a corresponding appearance in the score.
 * 
 * <p>Java class for principal-voice-symbol</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="principal-voice-symbol">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Hauptstimme"/>
 *     <enumeration value="Nebenstimme"/>
 *     <enumeration value="plain"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "principal-voice-symbol")
@XmlEnum
public enum PrincipalVoiceSymbol {

    @XmlEnumValue("Hauptstimme")
    HAUPTSTIMME("Hauptstimme"),
    @XmlEnumValue("Nebenstimme")
    NEBENSTIMME("Nebenstimme"),
    @XmlEnumValue("plain")
    PLAIN("plain"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    PrincipalVoiceSymbol(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static PrincipalVoiceSymbol fromValue(java.lang.String v) {
        for (PrincipalVoiceSymbol c: PrincipalVoiceSymbol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
