//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The root type indicates a pitch like C, D, E vs. a scale degree like 1, 2, 3. It is used with chord symbols in popular music. The root element has a root-step and optional root-alter element similar to the step and alter elements, but renamed to distinguish the different musical meanings.
 * 
 * <p>Java class for root complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="root">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="root-step" type="{}root-step"/>
 *         <element name="root-alter" type="{}harmony-alter" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "root", propOrder = {
    "rootStep",
    "rootAlter"
})
public class Root {

    @XmlElement(name = "root-step", required = true)
    protected RootStep rootStep;
    /**
     * The root-alter element represents the chromatic alteration of the root of the current chord within the harmony element. In some chord styles, the text for the root-step element may include root-alter information. In that case, the print-object attribute of the root-alter element can be set to no. The location attribute indicates whether the alteration should appear to the left or the right of the root-step; it is right by default.
     * 
     */
    @XmlElement(name = "root-alter")
    protected HarmonyAlter rootAlter;

    /**
     * Gets the value of the rootStep property.
     * 
     * @return
     *     possible object is
     *     {@link RootStep }
     *     
     */
    public RootStep getRootStep() {
        return rootStep;
    }

    /**
     * Sets the value of the rootStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link RootStep }
     *     
     */
    public void setRootStep(RootStep value) {
        this.rootStep = value;
    }

    /**
     * The root-alter element represents the chromatic alteration of the root of the current chord within the harmony element. In some chord styles, the text for the root-step element may include root-alter information. In that case, the print-object attribute of the root-alter element can be set to no. The location attribute indicates whether the alteration should appear to the left or the right of the root-step; it is right by default.
     * 
     * @return
     *     possible object is
     *     {@link HarmonyAlter }
     *     
     */
    public HarmonyAlter getRootAlter() {
        return rootAlter;
    }

    /**
     * Sets the value of the rootAlter property.
     * 
     * @param value
     *     allowed object is
     *     {@link HarmonyAlter }
     *     
     * @see #getRootAlter()
     */
    public void setRootAlter(HarmonyAlter value) {
        this.rootAlter = value;
    }

}
