//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The semi-pitched type represents categories of indefinite pitch for percussion instruments.
 * 
 * <p>Java class for semi-pitched</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="semi-pitched">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="high"/>
 *     <enumeration value="medium-high"/>
 *     <enumeration value="medium"/>
 *     <enumeration value="medium-low"/>
 *     <enumeration value="low"/>
 *     <enumeration value="very-low"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "semi-pitched")
@XmlEnum
public enum SemiPitched {

    @XmlEnumValue("high")
    HIGH("high"),
    @XmlEnumValue("medium-high")
    MEDIUM_HIGH("medium-high"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("medium-low")
    MEDIUM_LOW("medium-low"),
    @XmlEnumValue("low")
    LOW("low"),
    @XmlEnumValue("very-low")
    VERY_LOW("very-low");
    private final java.lang.String value;

    SemiPitched(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static SemiPitched fromValue(java.lang.String v) {
        for (SemiPitched c: SemiPitched.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
