//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The stick-material type represents the material being displayed in a stick pictogram.
 * 
 * <p>Java class for stick-material</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="stick-material">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="soft"/>
 *     <enumeration value="medium"/>
 *     <enumeration value="hard"/>
 *     <enumeration value="shaded"/>
 *     <enumeration value="x"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "stick-material")
@XmlEnum
public enum StickMaterial {

    @XmlEnumValue("soft")
    SOFT("soft"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("hard")
    HARD("hard"),
    @XmlEnumValue("shaded")
    SHADED("shaded"),
    @XmlEnumValue("x")
    X("x");
    private final java.lang.String value;

    StickMaterial(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static StickMaterial fromValue(java.lang.String v) {
        for (StickMaterial c: StickMaterial.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
