//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The stick-type type represents the shape of pictograms where the material in the stick, mallet, or beater is represented in the pictogram.
 * 
 * <p>Java class for stick-type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="stick-type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="bass drum"/>
 *     <enumeration value="double bass drum"/>
 *     <enumeration value="glockenspiel"/>
 *     <enumeration value="gum"/>
 *     <enumeration value="hammer"/>
 *     <enumeration value="superball"/>
 *     <enumeration value="timpani"/>
 *     <enumeration value="wound"/>
 *     <enumeration value="xylophone"/>
 *     <enumeration value="yarn"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "stick-type")
@XmlEnum
public enum StickType {

    @XmlEnumValue("bass drum")
    BASS_DRUM("bass drum"),
    @XmlEnumValue("double bass drum")
    DOUBLE_BASS_DRUM("double bass drum"),
    @XmlEnumValue("glockenspiel")
    GLOCKENSPIEL("glockenspiel"),
    @XmlEnumValue("gum")
    GUM("gum"),
    @XmlEnumValue("hammer")
    HAMMER("hammer"),
    @XmlEnumValue("superball")
    SUPERBALL("superball"),
    @XmlEnumValue("timpani")
    TIMPANI("timpani"),
    @XmlEnumValue("wound")
    WOUND("wound"),
    @XmlEnumValue("xylophone")
    XYLOPHONE("xylophone"),
    @XmlEnumValue("yarn")
    YARN("yarn");
    private final java.lang.String value;

    StickType(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static StickType fromValue(java.lang.String v) {
        for (StickType c: StickType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
