//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * Lyric hyphenation is indicated by the syllabic type. The single, begin, end, and middle values represent single-syllable words, word-beginning syllables, word-ending syllables, and mid-word syllables, respectively.
 * 
 * <p>Java class for syllabic</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="syllabic">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="single"/>
 *     <enumeration value="begin"/>
 *     <enumeration value="end"/>
 *     <enumeration value="middle"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "syllabic")
@XmlEnum
public enum Syllabic {

    @XmlEnumValue("single")
    SINGLE("single"),
    @XmlEnumValue("begin")
    BEGIN("begin"),
    @XmlEnumValue("end")
    END("end"),
    @XmlEnumValue("middle")
    MIDDLE("middle");
    private final java.lang.String value;

    Syllabic(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static Syllabic fromValue(java.lang.String v) {
        for (Syllabic c: Syllabic.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
