//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The symbol-size type is used to distinguish between full, cue sized, grace cue sized, and oversized symbols.
 * 
 * <p>Java class for symbol-size</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="symbol-size">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="full"/>
 *     <enumeration value="cue"/>
 *     <enumeration value="grace-cue"/>
 *     <enumeration value="large"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "symbol-size")
@XmlEnum
public enum SymbolSize {

    @XmlEnumValue("full")
    FULL("full"),
    @XmlEnumValue("cue")
    CUE("cue"),
    @XmlEnumValue("grace-cue")
    GRACE_CUE("grace-cue"),
    @XmlEnumValue("large")
    LARGE("large");
    private final java.lang.String value;

    SymbolSize(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static SymbolSize fromValue(java.lang.String v) {
        for (SymbolSize c: SymbolSize.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
