//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The sync-type type specifies the style that a score following application should use to synchronize an accompaniment with a performer. The none type indicates no synchronization to the performer. The tempo type indicates synchronization based on the performer tempo rather than individual events in the score. The event type indicates synchronization by following the performance of individual events in the score rather than the performer tempo. The mostly-tempo and mostly-event types combine these two approaches, with mostly-tempo giving more weight to tempo and mostly-event giving more weight to performed events. The always-event type provides the strictest synchronization by not being forgiving of missing performed events.
 * 
 * <p>Java class for sync-type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="sync-type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="none"/>
 *     <enumeration value="tempo"/>
 *     <enumeration value="mostly-tempo"/>
 *     <enumeration value="mostly-event"/>
 *     <enumeration value="event"/>
 *     <enumeration value="always-event"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "sync-type")
@XmlEnum
public enum SyncType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("tempo")
    TEMPO("tempo"),
    @XmlEnumValue("mostly-tempo")
    MOSTLY_TEMPO("mostly-tempo"),
    @XmlEnumValue("mostly-event")
    MOSTLY_EVENT("mostly-event"),
    @XmlEnumValue("event")
    EVENT("event"),
    @XmlEnumValue("always-event")
    ALWAYS_EVENT("always-event");
    private final java.lang.String value;

    SyncType(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static SyncType fromValue(java.lang.String v) {
        for (SyncType c: SyncType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
