//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The system-relation type distinguishes elements that are associated with a system rather than the particular part where the element appears. A value of only-top indicates that the element should appear only on the top part of the current system. A value of also-top indicates that the element should appear on both the current part and the top part of the current system. If this value appears in a score, when parts are created the element should only appear once in this part, not twice. A value of none indicates that the element is associated only with the current part, not with the system.
 * 
 * <p>Java class for system-relation</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="system-relation">
 *   <restriction base="{}system-relation-number">
 *     <enumeration value="only-top"/>
 *     <enumeration value="also-top"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "system-relation")
@XmlEnum(SystemRelationNumber.class)
public enum SystemRelation {

    @XmlEnumValue("only-top")
    ONLY_TOP(SystemRelationNumber.ONLY_TOP),
    @XmlEnumValue("also-top")
    ALSO_TOP(SystemRelationNumber.ALSO_TOP),
    @XmlEnumValue("none")
    NONE(SystemRelationNumber.NONE);
    private final SystemRelationNumber value;

    SystemRelation(SystemRelationNumber v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public SystemRelationNumber value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static SystemRelation fromValue(SystemRelationNumber v) {
        for (SystemRelation c: SystemRelation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
