//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The system-relation-number type distinguishes measure numbers that are associated with a system rather than the particular part where the element appears. A value of only-top or only-bottom indicates that the number should appear only on the top or bottom part of the current system, respectively. A value of also-top or also-bottom indicates that the number should appear on both the current part and the top or bottom part of the current system, respectively. If these values appear in a score, when parts are created the number should only appear once in this part, not twice. A value of none indicates that the number is associated only with the current part, not with the system.
 * 
 * <p>Java class for system-relation-number</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="system-relation-number">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="only-top"/>
 *     <enumeration value="only-bottom"/>
 *     <enumeration value="also-top"/>
 *     <enumeration value="also-bottom"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "system-relation-number")
@XmlEnum
public enum SystemRelationNumber {

    @XmlEnumValue("only-top")
    ONLY_TOP("only-top"),
    @XmlEnumValue("only-bottom")
    ONLY_BOTTOM("only-bottom"),
    @XmlEnumValue("also-top")
    ALSO_TOP("also-top"),
    @XmlEnumValue("also-bottom")
    ALSO_BOTTOM("also-bottom"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    SystemRelationNumber(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static SystemRelationNumber fromValue(java.lang.String v) {
        for (SystemRelationNumber c: SystemRelationNumber.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
