//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The time-symbol type indicates how to display a time signature. The normal value is the usual fractional display, and is the implied symbol type if none is specified. Other options are the common and cut time symbols, as well as a single number with an implied denominator. The note symbol indicates that the beat-type should be represented with the corresponding downstem note rather than a number. The dotted-note symbol indicates that the beat-type should be represented with a dotted downstem note that corresponds to three times the beat-type value, and a numerator that is one third the beats value.
 * 
 * <p>Java class for time-symbol</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="time-symbol">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="common"/>
 *     <enumeration value="cut"/>
 *     <enumeration value="single-number"/>
 *     <enumeration value="note"/>
 *     <enumeration value="dotted-note"/>
 *     <enumeration value="normal"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "time-symbol")
@XmlEnum
public enum TimeSymbol {

    @XmlEnumValue("common")
    COMMON("common"),
    @XmlEnumValue("cut")
    CUT("cut"),
    @XmlEnumValue("single-number")
    SINGLE_NUMBER("single-number"),
    @XmlEnumValue("note")
    NOTE("note"),
    @XmlEnumValue("dotted-note")
    DOTTED_NOTE("dotted-note"),
    @XmlEnumValue("normal")
    NORMAL("normal");
    private final java.lang.String value;

    TimeSymbol(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static TimeSymbol fromValue(java.lang.String v) {
        for (TimeSymbol c: TimeSymbol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
