//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The time-relation type indicates the symbol used to represent the interchangeable aspect of dual time signatures.
 * 
 * <p>Java class for time-relation</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="time-relation">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="parentheses"/>
 *     <enumeration value="bracket"/>
 *     <enumeration value="equals"/>
 *     <enumeration value="slash"/>
 *     <enumeration value="space"/>
 *     <enumeration value="hyphen"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "time-relation")
@XmlEnum
public enum TimeRelation {

    @XmlEnumValue("parentheses")
    PARENTHESES("parentheses"),
    @XmlEnumValue("bracket")
    BRACKET("bracket"),
    @XmlEnumValue("equals")
    EQUALS("equals"),
    @XmlEnumValue("slash")
    SLASH("slash"),
    @XmlEnumValue("space")
    SPACE("space"),
    @XmlEnumValue("hyphen")
    HYPHEN("hyphen");
    private final java.lang.String value;

    TimeRelation(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static TimeRelation fromValue(java.lang.String v) {
        for (TimeRelation c: TimeRelation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
