//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Time modification indicates tuplets, double-note tremolos, and other durational changes. A time-modification element shows how the cumulative, sounding effect of tuplets and double-note tremolos compare to the written note type represented by the type and dot elements. Nested tuplets and other notations that use more detailed information need both the time-modification and tuplet elements to be represented accurately.
 * 
 * <p>Java class for time-modification complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="time-modification">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="actual-notes" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         <element name="normal-notes" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         <sequence minOccurs="0">
 *           <element name="normal-type" type="{}note-type-value"/>
 *           <element name="normal-dot" type="{}empty" maxOccurs="unbounded" minOccurs="0"/>
 *         </sequence>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "time-modification", propOrder = {
    "actualNotes",
    "normalNotes",
    "normalType",
    "normalDot"
})
@XmlSeeAlso({
    MetronomeTuplet.class
})
public class TimeModification {

    /**
     * The actual-notes element describes how many notes are played in the time usually occupied by the number in the normal-notes element.
     * 
     */
    @XmlElement(name = "actual-notes", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger actualNotes;
    /**
     * The normal-notes element describes how many notes are usually played in the time occupied by the number in the actual-notes element.
     * 
     */
    @XmlElement(name = "normal-notes", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger normalNotes;
    /**
     * If the type associated with the number in the normal-notes element is different than the current note type (e.g., a quarter note within an eighth note triplet), then the normal-notes type (e.g. eighth) is specified in the normal-type and normal-dot elements.
     * 
     */
    @XmlElement(name = "normal-type")
    protected java.lang.String normalType;
    /**
     * The normal-dot element is used to specify dotted normal tuplet types.
     * 
     */
    @XmlElement(name = "normal-dot")
    protected List<Empty> normalDot;

    /**
     * The actual-notes element describes how many notes are played in the time usually occupied by the number in the normal-notes element.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActualNotes() {
        return actualNotes;
    }

    /**
     * Sets the value of the actualNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getActualNotes()
     */
    public void setActualNotes(BigInteger value) {
        this.actualNotes = value;
    }

    /**
     * The normal-notes element describes how many notes are usually played in the time occupied by the number in the actual-notes element.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNormalNotes() {
        return normalNotes;
    }

    /**
     * Sets the value of the normalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getNormalNotes()
     */
    public void setNormalNotes(BigInteger value) {
        this.normalNotes = value;
    }

    /**
     * If the type associated with the number in the normal-notes element is different than the current note type (e.g., a quarter note within an eighth note triplet), then the normal-notes type (e.g. eighth) is specified in the normal-type and normal-dot elements.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getNormalType() {
        return normalType;
    }

    /**
     * Sets the value of the normalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     * @see #getNormalType()
     */
    public void setNormalType(java.lang.String value) {
        this.normalType = value;
    }

    /**
     * The normal-dot element is used to specify dotted normal tuplet types.
     * 
     * Gets the value of the normalDot property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the normalDot property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNormalDot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Empty }
     * </p>
     * 
     * 
     * @return
     *     The value of the normalDot property.
     */
    public List<Empty> getNormalDot() {
        if (normalDot == null) {
            normalDot = new ArrayList<>();
        }
        return this.normalDot;
    }

}
