//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The upright-inverted type describes the appearance of a fermata element. The value is upright if not specified.
 * 
 * <p>Java class for upright-inverted</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="upright-inverted">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="upright"/>
 *     <enumeration value="inverted"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "upright-inverted")
@XmlEnum
public enum UprightInverted {

    @XmlEnumValue("upright")
    UPRIGHT("upright"),
    @XmlEnumValue("inverted")
    INVERTED("inverted");
    private final java.lang.String value;

    UprightInverted(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static UprightInverted fromValue(java.lang.String v) {
        for (UprightInverted c: UprightInverted.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
