//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The virtual-instrument element defines a specific virtual instrument used for an instrument sound.
 * 
 * <p>Java class for virtual-instrument complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="virtual-instrument">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="virtual-library" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="virtual-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "virtual-instrument", propOrder = {
    "virtualLibrary",
    "virtualName"
})
public class VirtualInstrument {

    /**
     * The virtual-library element indicates the virtual instrument library name.
     * 
     */
    @XmlElement(name = "virtual-library")
    protected java.lang.String virtualLibrary;
    /**
     * The virtual-name element indicates the library-specific name for the virtual instrument.
     * 
     */
    @XmlElement(name = "virtual-name")
    protected java.lang.String virtualName;

    /**
     * The virtual-library element indicates the virtual instrument library name.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getVirtualLibrary() {
        return virtualLibrary;
    }

    /**
     * Sets the value of the virtualLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     * @see #getVirtualLibrary()
     */
    public void setVirtualLibrary(java.lang.String value) {
        this.virtualLibrary = value;
    }

    /**
     * The virtual-name element indicates the library-specific name for the virtual instrument.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getVirtualName() {
        return virtualName;
    }

    /**
     * Sets the value of the virtualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     * @see #getVirtualName()
     */
    public void setVirtualName(java.lang.String value) {
        this.virtualName = value;
    }

}
