//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The winged attribute indicates whether the repeat has winged extensions that appear above and below the barline. The straight and curved values represent single wings, while the double-straight and double-curved values represent double wings. The none value indicates no wings and is the default.
 * 
 * <p>Java class for winged</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="winged">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="none"/>
 *     <enumeration value="straight"/>
 *     <enumeration value="curved"/>
 *     <enumeration value="double-straight"/>
 *     <enumeration value="double-curved"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "winged")
@XmlEnum
public enum Winged {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("straight")
    STRAIGHT("straight"),
    @XmlEnumValue("curved")
    CURVED("curved"),
    @XmlEnumValue("double-straight")
    DOUBLE_STRAIGHT("double-straight"),
    @XmlEnumValue("double-curved")
    DOUBLE_CURVED("double-curved");
    private final java.lang.String value;

    Winged(java.lang.String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public java.lang.String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static Winged fromValue(java.lang.String v) {
        for (Winged c: Winged.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
